"""add job worker leases

Revision ID: 177ea08cc805
Revises: 2624aaa6dd5c
Create Date: 2026-09-19 10:17:29.108023
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '177ea08cc805'
down_revision: Union[str, Sequence[str], None] = '2624aaa6dd5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('lease_owner', sa.String(length=160), nullable=True))
    op.add_column('jobs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'attempt_count')
    op.drop_column('jobs', 'lease_expires_at')
    op.drop_column('jobs', 'lease_owner')
    # ### end Alembic commands ###
