"""initial registry schema

Revision ID: 2624aaa6dd5c
Revises: 
Create Date: 2026-09-19 10:09:25.197540
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2624aaa6dd5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('task_kind', sa.String(length=50), nullable=False),
    sa.Column('storage_root', sa.Text(), nullable=True),
    sa.Column('git_url', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.String(length=200), nullable=True),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('recipe_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('logical_name', sa.String(length=200), nullable=False),
    sa.Column('owner_type', sa.String(length=40), nullable=True),
    sa.Column('owner_id', sa.String(length=40), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('managed_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_owner_id'), 'artifacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_artifacts_owner_type'), 'artifacts', ['owner_type'], unique=False)
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=False),
    sa.Column('after_json', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('parent_dataset_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('task_kind', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=False),
    sa.Column('manifest_path', sa.Text(), nullable=True),
    sa.Column('annotation_path', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('class_names', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_dataset_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_parent_dataset_id'), 'dataset_versions', ['parent_dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_project_id'), 'dataset_versions', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('runner_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('command', sa.JSON(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('recipe_id', sa.String(length=120), nullable=False),
    sa.Column('recipe_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_sessions_project_id'), 'onboarding_sessions', ['project_id'], unique=True)
    op.create_table('runner_profiles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('executable', sa.Text(), nullable=False),
    sa.Column('default_args', sa.JSON(), nullable=False),
    sa.Column('working_directory', sa.Text(), nullable=True),
    sa.Column('environment_names', sa.JSON(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runner_profiles_project_id'), 'runner_profiles', ['project_id'], unique=False)
    op.create_table('storage_mappings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('root_path', sa.Text(), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('last_validation', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_mappings_project_id'), 'storage_mappings', ['project_id'], unique=False)
    op.create_table('target_profiles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('target_kind', sa.String(length=80), nullable=False),
    sa.Column('runtime', sa.String(length=120), nullable=False),
    sa.Column('hardware', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_profiles_project_id'), 'target_profiles', ['project_id'], unique=False)
    op.create_table('calibration_set_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('dataset_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('sampling', sa.JSON(), nullable=False),
    sa.Column('preprocessing', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_set_versions_project_id'), 'calibration_set_versions', ['project_id'], unique=False)
    op.create_table('data_assets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('storage_id', sa.String(length=40), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage_mappings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_assets_project_id'), 'data_assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_data_assets_storage_id'), 'data_assets', ['storage_id'], unique=False)
    op.create_table('evaluation_set_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('dataset_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_set_versions_project_id'), 'evaluation_set_versions', ['project_id'], unique=False)
    op.create_table('label_schema_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('parent_label_schema_id', sa.String(length=40), nullable=True),
    sa.Column('dataset_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('classes', sa.JSON(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_label_schema_id'], ['label_schema_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_schema_versions_parent_label_schema_id'), 'label_schema_versions', ['parent_label_schema_id'], unique=False)
    op.create_index(op.f('ix_label_schema_versions_project_id'), 'label_schema_versions', ['project_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=False),
    sa.Column('task_kind', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('precision', sa.String(length=50), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('config_path', sa.Text(), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('config_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_dataset_id', sa.String(length=40), nullable=True),
    sa.Column('source_run_id', sa.String(length=40), nullable=True),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('runnable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_project_id'), 'model_versions', ['project_id'], unique=False)
    op.create_table('split_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('dataset_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_split_versions_project_id'), 'split_versions', ['project_id'], unique=False)
    op.create_table('step_progress',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('step_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_progress_session_id'), 'step_progress', ['session_id'], unique=False)
    op.create_table('field_data_batches',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_model_id', sa.String(length=40), nullable=True),
    sa.Column('source_dataset_id', sa.String(length=40), nullable=True),
    sa.Column('candidate_dataset_id', sa.String(length=40), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('prediction_path', sa.Text(), nullable=True),
    sa.Column('label_path', sa.Text(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_dataset_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['source_model_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_data_batches_project_id'), 'field_data_batches', ['project_id'], unique=False)
    op.create_table('model_alias_history',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=False),
    sa.Column('previous_alias', sa.String(length=50), nullable=True),
    sa.Column('new_alias', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_alias_history_model_id'), 'model_alias_history', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_alias_history_project_id'), 'model_alias_history', ['project_id'], unique=False)
    op.create_table('quantization_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('source_model_id', sa.String(length=40), nullable=False),
    sa.Column('output_model_id', sa.String(length=40), nullable=True),
    sa.Column('calibration_set_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_role', sa.String(length=40), nullable=False),
    sa.Column('output_role', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('weight_dtype', sa.String(length=40), nullable=False),
    sa.Column('activation_dtype', sa.String(length=40), nullable=False),
    sa.Column('encoding_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calibration_set_id'], ['calibration_set_versions.id'], ),
    sa.ForeignKeyConstraint(['output_model_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_model_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantization_runs_project_id'), 'quantization_runs', ['project_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dataset_id', sa.String(length=40), nullable=True),
    sa.Column('model_id', sa.String(length=40), nullable=True),
    sa.Column('parent_run_id', sa.String(length=40), nullable=True),
    sa.Column('external_run_id', sa.String(length=200), nullable=True),
    sa.Column('import_hash', sa.String(length=128), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('environment', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_external_run_id'), 'runs', ['external_run_id'], unique=False)
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_table('board_benchmarks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=False),
    sa.Column('target_profile_id', sa.String(length=40), nullable=False),
    sa.Column('evaluation_run_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('measurement', sa.JSON(), nullable=False),
    sa.Column('raw_output_path', sa.Text(), nullable=True),
    sa.Column('raw_output_hash', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['target_profile_id'], ['target_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_benchmarks_project_id'), 'board_benchmarks', ['project_id'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=False),
    sa.Column('evaluation_run_id', sa.String(length=40), nullable=True),
    sa.Column('baseline_model_id', sa.String(length=40), nullable=True),
    sa.Column('gate_config', sa.JSON(), nullable=False),
    sa.Column('gate_result', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_model_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_project_id'), 'releases', ['project_id'], unique=False)
    op.create_table('release_evidence',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('release_id', sa.String(length=40), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=40), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_evidence_project_id'), 'release_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_release_evidence_release_id'), 'release_evidence', ['release_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_evidence_release_id'), table_name='release_evidence')
    op.drop_index(op.f('ix_release_evidence_project_id'), table_name='release_evidence')
    op.drop_table('release_evidence')
    op.drop_index(op.f('ix_releases_project_id'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_board_benchmarks_project_id'), table_name='board_benchmarks')
    op.drop_table('board_benchmarks')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_external_run_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_quantization_runs_project_id'), table_name='quantization_runs')
    op.drop_table('quantization_runs')
    op.drop_index(op.f('ix_model_alias_history_project_id'), table_name='model_alias_history')
    op.drop_index(op.f('ix_model_alias_history_model_id'), table_name='model_alias_history')
    op.drop_table('model_alias_history')
    op.drop_index(op.f('ix_field_data_batches_project_id'), table_name='field_data_batches')
    op.drop_table('field_data_batches')
    op.drop_index(op.f('ix_step_progress_session_id'), table_name='step_progress')
    op.drop_table('step_progress')
    op.drop_index(op.f('ix_split_versions_project_id'), table_name='split_versions')
    op.drop_table('split_versions')
    op.drop_index(op.f('ix_model_versions_project_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_label_schema_versions_project_id'), table_name='label_schema_versions')
    op.drop_index(op.f('ix_label_schema_versions_parent_label_schema_id'), table_name='label_schema_versions')
    op.drop_table('label_schema_versions')
    op.drop_index(op.f('ix_evaluation_set_versions_project_id'), table_name='evaluation_set_versions')
    op.drop_table('evaluation_set_versions')
    op.drop_index(op.f('ix_data_assets_storage_id'), table_name='data_assets')
    op.drop_index(op.f('ix_data_assets_project_id'), table_name='data_assets')
    op.drop_table('data_assets')
    op.drop_index(op.f('ix_calibration_set_versions_project_id'), table_name='calibration_set_versions')
    op.drop_table('calibration_set_versions')
    op.drop_index(op.f('ix_target_profiles_project_id'), table_name='target_profiles')
    op.drop_table('target_profiles')
    op.drop_index(op.f('ix_storage_mappings_project_id'), table_name='storage_mappings')
    op.drop_table('storage_mappings')
    op.drop_index(op.f('ix_runner_profiles_project_id'), table_name='runner_profiles')
    op.drop_table('runner_profiles')
    op.drop_index(op.f('ix_onboarding_sessions_project_id'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_dataset_versions_project_id'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_parent_dataset_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_owner_type'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_owner_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('projects')
    # ### end Alembic commands ###
